const express = require('express');
const multer = require('multer');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const os = require('os');
const mammoth = require('mammoth');
const PDFDocument = require('pdfkit');

const app = express();

// Get local IP addresses
const networkInterfaces = os.networkInterfaces();
const ipAddresses = [];

for (const interfaceName in networkInterfaces) {
    const interfaces = networkInterfaces[interfaceName];
    for (const iface of interfaces) {
        if (iface.family === 'IPv4' && !iface.internal) {
            ipAddresses.push(iface.address);
        }
    }
}

// CORS configuration
app.use(cors({
    origin: '*',
    methods: ['GET', 'POST', 'OPTIONS'],
    allowedHeaders: ['Content-Type', 'Accept']
}));

// Parse JSON
app.use(express.json());

// Configure multer for file uploads
const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        const uploadDir = path.join(__dirname, 'uploads');
        if (!fs.existsSync(uploadDir)) {
            fs.mkdirSync(uploadDir, { recursive: true });
        }
        cb(null, uploadDir);
    },
    filename: function (req, file, cb) {
        const timestamp = Date.now();
        const cleanName = file.originalname.replace(/[^a-zA-Z0-9.]/g, '_');
        cb(null, `${timestamp}-${cleanName}`);
    }
});

const upload = multer({ 
    storage: storage,
    limits: { fileSize: 20 * 1024 * 1024 }, // 20MB
    fileFilter: (req, file, cb) => {
        const allowedTypes = ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'];
        const allowedExt = ['.pdf', '.doc', '.docx', '.txt'];
        
        const ext = path.extname(file.originalname).toLowerCase();
        
        if (allowedTypes.includes(file.mimetype) || allowedExt.includes(ext)) {
            cb(null, true);
        } else {
            cb(new Error('Invalid file type. Please upload PDF, DOC, DOCX, or TXT files.'));
        }
    }
});

// ============ PDF GENERATION FUNCTION ============

function generatePDF(resumeData, enhancements, res) {
    return new Promise((resolve, reject) => {
        try {
            // Create a PDF document
            const doc = new PDFDocument({
                margins: {
                    top: 50,
                    bottom: 50,
                    left: 50,
                    right: 50
                },
                size: 'A4'
            });
            
            // Set response headers
            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', 'attachment; filename=enhanced-resume.pdf');
            
            // Pipe PDF to response
            doc.pipe(res);
            
            // Add title
            doc.fontSize(24)
               .font('Helvetica-Bold')
               .text('AI ENHANCED RESUME', { align: 'center' })
               .moveDown();
            
            doc.fontSize(12)
               .font('Helvetica')
               .text('Generated by AI Resume Builder', { align: 'center' })
               .moveDown(2);
            
            // Personal Information
            if (resumeData.personalInfo) {
                doc.fontSize(16)
                   .font('Helvetica-Bold')
                   .fillColor('#667eea')
                   .text('📋 PERSONAL INFORMATION')
                   .moveDown(0.5)
                   .fontSize(12)
                   .font('Helvetica')
                   .fillColor('black');
                
                if (resumeData.personalInfo.name) {
                    doc.text(`Name: ${resumeData.personalInfo.name}`);
                }
                if (resumeData.personalInfo.email) {
                    doc.text(`Email: ${resumeData.personalInfo.email}`);
                }
                if (resumeData.personalInfo.phone) {
                    doc.text(`Phone: ${resumeData.personalInfo.phone}`);
                }
                if (resumeData.personalInfo.location) {
                    doc.text(`Location: ${resumeData.personalInfo.location}`);
                }
                doc.moveDown();
            }
            
            // Professional Summary (if enhanced)
            if (enhancements && enhancements.summary) {
                doc.fontSize(16)
                   .font('Helvetica-Bold')
                   .fillColor('#667eea')
                   .text('✨ PROFESSIONAL SUMMARY')
                   .moveDown(0.5)
                   .fontSize(12)
                   .font('Helvetica')
                   .fillColor('black')
                   .text(enhancements.summary)
                   .moveDown();
            }
            
            // Skills
            if (enhancements && enhancements.skills) {
                doc.fontSize(16)
                   .font('Helvetica-Bold')
                   .fillColor('#667eea')
                   .text('🔧 SKILLS')
                   .moveDown(0.5)
                   .fontSize(12)
                   .font('Helvetica')
                   .fillColor('black');
                
                const skillsLines = enhancements.skills.split('\n');
                skillsLines.forEach(line => {
                    if (line.trim()) {
                        doc.text(line);
                    }
                });
                doc.moveDown();
            } else if (resumeData.skills && resumeData.skills.length > 0) {
                doc.fontSize(16)
                   .font('Helvetica-Bold')
                   .fillColor('#667eea')
                   .text('🔧 SKILLS')
                   .moveDown(0.5)
                   .fontSize(12)
                   .font('Helvetica')
                   .fillColor('black')
                   .text(resumeData.skills.join(', '))
                   .moveDown();
            }
            
            // Experience
            if (enhancements && enhancements.experience) {
                doc.fontSize(16)
                   .font('Helvetica-Bold')
                   .fillColor('#667eea')
                   .text('💼 WORK EXPERIENCE')
                   .moveDown(0.5)
                   .fontSize(12)
                   .font('Helvetica')
                   .fillColor('black');
                
                const expLines = enhancements.experience.split('\n');
                expLines.forEach(line => {
                    if (line.trim()) {
                        doc.text(line);
                    }
                });
                doc.moveDown();
            } else if (resumeData.experience && resumeData.experience.length > 0) {
                doc.fontSize(16)
                   .font('Helvetica-Bold')
                   .fillColor('#667eea')
                   .text('💼 WORK EXPERIENCE')
                   .moveDown(0.5)
                   .fontSize(12)
                   .font('Helvetica')
                   .fillColor('black')
                   .text(resumeData.experience[0].description)
                   .moveDown();
            }
            
            // Projects
            if (enhancements && enhancements.projects) {
                doc.fontSize(16)
                   .font('Helvetica-Bold')
                   .fillColor('#667eea')
                   .text('🚀 PROJECTS')
                   .moveDown(0.5)
                   .fontSize(12)
                   .font('Helvetica')
                   .fillColor('black');
                
                const projLines = enhancements.projects.split('\n');
                projLines.forEach(line => {
                    if (line.trim()) {
                        doc.text(line);
                    }
                });
                doc.moveDown();
            } else if (resumeData.projects && resumeData.projects.length > 0) {
                doc.fontSize(16)
                   .font('Helvetica-Bold')
                   .fillColor('#667eea')
                   .text('🚀 PROJECTS')
                   .moveDown(0.5)
                   .fontSize(12)
                   .font('Helvetica')
                   .fillColor('black')
                   .text(resumeData.projects[0].description)
                   .moveDown();
            }
            
            // Education
            if (resumeData.education && resumeData.education.length > 0) {
                doc.fontSize(16)
                   .font('Helvetica-Bold')
                   .fillColor('#667eea')
                   .text('🎓 EDUCATION')
                   .moveDown(0.5)
                   .fontSize(12)
                   .font('Helvetica')
                   .fillColor('black')
                   .text(resumeData.education[0].description)
                   .moveDown();
            }
            
            // Achievements (if enhanced)
            if (enhancements && enhancements.achievements) {
                doc.fontSize(16)
                   .font('Helvetica-Bold')
                   .fillColor('#667eea')
                   .text('🏆 ACHIEVEMENTS')
                   .moveDown(0.5)
                   .fontSize(12)
                   .font('Helvetica')
                   .fillColor('black');
                
                const achLines = enhancements.achievements.split('\n');
                achLines.forEach(line => {
                    if (line.trim()) {
                        doc.text(line);
                    }
                });
            }
            
            // Footer
            doc.moveDown(2)
               .fontSize(10)
               .font('Helvetica-Oblique')
               .fillColor('gray')
               .text('Generated by AI Resume Builder - ATS Optimized', { align: 'center' });
            
            // Finalize PDF
            doc.end();
            
            // Resolve when done
            doc.on('finish', resolve);
            doc.on('error', reject);
            
        } catch (error) {
            reject(error);
        }
    });
}

// ============ MOCK AI ENHANCEMENT FUNCTIONS ============

function getMockEnhancement(section, resumeData) {
    const name = resumeData.personalInfo?.name || 'Professional';
    const skills = resumeData.skills || ['JavaScript', 'Python', 'React', 'Node.js', 'SQL'];
    const experience = resumeData.experience?.[0]?.description || 'Software Developer';
    const projects = resumeData.projects?.[0]?.description || 'Web Application';
    
    switch(section) {
        case 'summary':
            return `Results-driven ${skills[0] || 'Software'} Developer with ${skills.length}+ years of experience in ${skills.slice(0,3).join(', ')}. Proven track record of delivering high-quality solutions, improving system performance by 30%, and leading cross-functional teams. Passionate about writing clean, maintainable code and adopting emerging technologies to solve complex business problems.`;
        
        case 'experience':
            if (resumeData.experience && resumeData.experience.length > 0) {
                return `• ${resumeData.experience[0].description}
• Led development of 5+ major features resulting in 40% increase in user engagement
• Implemented CI/CD pipeline reducing deployment time from 2 hours to 15 minutes
• Mentored 4 junior developers and conducted weekly code reviews
• Collaborated with product managers to define technical requirements and deliverables
• Optimized database queries improving API response time by 60%
• Received "Employee of the Quarter" award for exceptional performance`;
            }
            return `• ${experience}
• Developed and maintained 10+ web applications using modern frameworks
• Improved application performance and reduced load times by 45%
• Collaborated with cross-functional teams to deliver projects on schedule
• Participated in agile ceremonies and contributed to sprint planning
• Implemented automated testing increasing code coverage to 85%`;
        
        case 'skills':
            const techSkills = skills.slice(0,6).join(', ');
            return `TECHNICAL SKILLS
• Programming Languages: ${skills.slice(0,4).join(', ')}
• Frameworks & Libraries: React, Node.js, Express, Django
• Databases: MongoDB, PostgreSQL, MySQL, Redis
• Cloud & DevOps: AWS (EC2, S3), Docker, Jenkins, Git
• Tools: VS Code, Postman, JIRA, Figma

SOFT SKILLS
• Team Leadership & Mentoring
• Technical Communication
• Problem Solving & Analytical Thinking
• Project Management & Agile Methodologies
• Time Management & Adaptability`;
        
        case 'projects':
            if (resumeData.projects && resumeData.projects.length > 0) {
                return `• ${resumeData.projects[0].description}
• Built using ${skills.slice(0,3).join(', ')} with responsive mobile-first design
• Implemented authentication, payment processing, and real-time notifications
• Achieved 99.9% uptime and served 10,000+ active users
• Open-sourced on GitHub with 200+ stars and community contributions
• Integrated third-party APIs including Stripe, Google Maps, and SendGrid
• Deployed on AWS using EC2 and S3 with automated CI/CD pipeline`;
            }
            return `• ${projects}
• Developed full-stack application using MERN stack (MongoDB, Express, React, Node.js)
• Integrated third-party APIs for enhanced functionality (Payment, Maps, Email)
• Implemented responsive UI with modern design patterns and accessibility standards
• Deployed to cloud platform with automated CI/CD pipeline using GitHub Actions
• Wrote comprehensive documentation and achieved 90% test coverage
• Featured in "Project of the Month" for innovative approach and clean code`;
        
        case 'achievements':
            return `• Increased team productivity by 35% through process improvements
• Reduced bug count by 50% by implementing code review standards
• Successfully delivered 15+ projects on time and under budget
• Presented technical workshops to 50+ developers
• Contributed to open-source projects with 1000+ downloads`;
        
        default:
            return 'Enhanced content would appear here. The AI enhancement system is working in mock mode.';
    }
}

function enhanceResume(resumeData) {
    const enhancements = {};
    const sections = ['summary', 'experience', 'skills', 'projects', 'achievements'];
    
    sections.forEach(section => {
        enhancements[section] = getMockEnhancement(section, resumeData);
    });
    
    return enhancements;
}

// ============ ATS SCORING FUNCTION ============

function calculateATSScore(resumeData) {
    let score = 70;
    const feedback = [];
    const suggestions = [];
    
    if (resumeData.personalInfo?.name) score += 5;
    else suggestions.push("Add your full name");
    
    if (resumeData.personalInfo?.email) score += 3;
    else suggestions.push("Add your email address");
    
    if (resumeData.personalInfo?.phone) score += 2;
    else suggestions.push("Add your phone number");
    
    if (resumeData.skills && resumeData.skills.length > 0) {
        score += Math.min(resumeData.skills.length * 2, 15);
        if (resumeData.skills.length < 5) {
            suggestions.push("Add more relevant skills (aim for 8-10 skills)");
        }
    } else {
        suggestions.push("Add your skills section");
    }
    
    if (resumeData.education && resumeData.education.length > 0) {
        score += 10;
        if (!resumeData.education[0].description?.includes('20')) {
            suggestions.push("Add graduation year to education");
        }
    } else {
        suggestions.push("Add your education details");
    }
    
    if (resumeData.experience && resumeData.experience.length > 0) {
        score += 15;
        if (resumeData.experience[0].description?.length < 50) {
            suggestions.push("Add more details to your experience (use bullet points)");
        }
        if (!resumeData.experience[0].description?.match(/\d+/)) {
            suggestions.push("Include metrics and numbers in your experience");
        }
    } else {
        suggestions.push("Add your work experience");
    }
    
    if (resumeData.projects && resumeData.projects.length > 0) {
        score += 10;
    } else {
        suggestions.push("Add projects to showcase your work");
    }
    
    if (score >= 90) {
        feedback.push("Excellent resume! Well-optimized for ATS.");
        feedback.push("Strong keyword presence throughout.");
        feedback.push("Good use of metrics and achievements.");
    } else if (score >= 75) {
        feedback.push("Good resume with room for improvement.");
        feedback.push("Consider adding more industry keywords.");
        feedback.push("Add more quantifiable achievements.");
    } else {
        feedback.push("Resume needs optimization for ATS.");
        feedback.push("Add more relevant keywords from job descriptions.");
        feedback.push("Strengthen your experience descriptions.");
    }
    
    return {
        score: Math.min(100, score),
        feedback: feedback.slice(0, 3),
        suggestions: suggestions.slice(0, 5)
    };
}

// ============ RESUME PARSING FUNCTIONS ============

async function parsePDF(filePath) {
    try {
        const fileName = path.basename(filePath);
        return `Resume PDF: ${fileName}\n\nThis is a parsed PDF resume. In production, use pdf-parse library.`;
    } catch (error) {
        return `PDF parsing error: ${error.message}`;
    }
}

async function parseWord(filePath) {
    try {
        const result = await mammoth.extractRawText({ path: filePath });
        return result.value;
    } catch (error) {
        return `Word document parsed (filename: ${path.basename(filePath)})`;
    }
}

function extractResumeData(text) {
    const data = {
        personalInfo: {},
        skills: [],
        education: [],
        experience: [],
        projects: []
    };
    
    const emailMatch = text.match(/[\w.-]+@[\w.-]+\.\w+/);
    if (emailMatch) data.personalInfo.email = emailMatch[0];
    
    const phoneMatch = text.match(/(\+\d{1,3}[-.]?)?\(?\d{3}\)?[-.]?\d{3}[-.]?\d{4}/);
    if (phoneMatch) data.personalInfo.phone = phoneMatch[0];
    
    const lines = text.split('\n').filter(l => l.trim().length > 0);
    if (lines.length > 0) data.personalInfo.name = lines[0].trim();
    
    const commonSkills = [
        'JavaScript', 'Python', 'Java', 'C++', 'React', 'Node.js', 
        'HTML', 'CSS', 'SQL', 'MongoDB', 'AWS', 'Git', 'Docker',
        'TypeScript', 'Angular', 'Vue', 'PHP', 'Ruby', 'C#', 'Swift',
        'Kotlin', 'Flutter', 'TensorFlow', 'PyTorch', 'Kubernetes'
    ];
    
    data.skills = commonSkills.filter(skill => 
        text.toLowerCase().includes(skill.toLowerCase())
    );
    
    if (data.skills.length === 0) {
        data.skills = ['JavaScript', 'Python', 'React', 'Node.js', 'SQL'];
    }
    
    if (text.toLowerCase().includes('bachelor') || text.toLowerCase().includes('master') || 
        text.toLowerCase().includes('university') || text.toLowerCase().includes('college')) {
        data.education.push({ description: "Education information found in resume" });
    } else {
        data.education.push({ description: "Please add your education details" });
    }
    
    if (text.toLowerCase().includes('experience') || text.toLowerCase().includes('work')) {
        data.experience.push({ description: "Experience information found in resume" });
    } else {
        data.experience.push({ description: "Please add your work experience" });
    }
    
    return data;
}

// ============ API ENDPOINTS ============

app.get('/', (req, res) => {
    res.json({
        name: 'AI Resume Builder API',
        status: 'running',
        version: '1.0',
        endpoints: {
            upload: 'POST /api/upload - Upload resume file',
            manual: 'POST /api/manual-entry - Submit resume manually',
            enhance: 'POST /api/enhance - Enhance resume with AI',
            ats: 'POST /api/ats-score - Get ATS score',
            download: 'POST /api/download-pdf - Download resume as PDF',
            chat: 'POST /api/chat - AI chat assistant',
            test: 'GET /api/test - Test connection'
        }
    });
});

app.get('/api/test', (req, res) => {
    res.json({ 
        success: true, 
        message: 'Server is running',
        time: new Date().toISOString()
    });
});

// Upload endpoint
app.post('/api/upload', upload.single('resume'), async (req, res) => {
    try {
        if (!req.file) {
            return res.status(400).json({ success: false, error: 'No file uploaded' });
        }
        
        console.log('✅ File received:', req.file.originalname);
        
        let extractedText = '';
        const fileExt = path.extname(req.file.originalname).toLowerCase();
        
        if (fileExt === '.pdf') {
            extractedText = await parsePDF(req.file.path);
        } else if (['.doc', '.docx'].includes(fileExt)) {
            extractedText = await parseWord(req.file.path);
        } else {
            extractedText = `File uploaded: ${req.file.originalname}`;
        }
        
        const resumeData = extractResumeData(extractedText);
        const atsScore = calculateATSScore(resumeData);
        
        res.json({
            success: true,
            message: 'Resume uploaded and parsed successfully',
            data: resumeData,
            atsScore: atsScore,
            file: {
                name: req.file.originalname,
                size: req.file.size,
                type: req.file.mimetype
            }
        });
        
    } catch (error) {
        console.error('Upload error:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// Manual entry
app.post('/api/manual-entry', (req, res) => {
    try {
        const { personalInfo, skills, education, experience, projects, achievements } = req.body;
        
        const resumeData = {
            personalInfo: personalInfo || { name: '', email: '', phone: '', location: '' },
            skills: skills || [],
            education: education || [{ description: '' }],
            experience: experience || [{ description: '' }],
            projects: projects || [{ description: '' }],
            achievements: achievements || ''
        };
        
        const atsScore = calculateATSScore(resumeData);
        
        res.json({
            success: true,
            message: 'Manual entry received',
            data: resumeData,
            atsScore: atsScore
        });
        
    } catch (error) {
        console.error('Manual entry error:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// AI Enhancement endpoint
app.post('/api/enhance', (req, res) => {
    try {
        const { resumeData } = req.body;
        
        if (!resumeData) {
            return res.status(400).json({ success: false, error: 'No resume data provided' });
        }
        
        const enhancements = enhanceResume(resumeData);
        const newScore = calculateATSScore(resumeData);
        
        res.json({
            success: true,
            message: 'Resume enhanced successfully (mock mode)',
            original: resumeData,
            enhancements: enhancements,
            atsScore: newScore
        });
        
    } catch (error) {
        console.error('Enhancement error:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// PDF Download endpoint
app.post('/api/download-pdf', (req, res) => {
    try {
        const { resumeData, enhancements } = req.body;
        
        if (!resumeData) {
            return res.status(400).json({ success: false, error: 'No resume data provided' });
        }
        
        // Generate and send PDF
        generatePDF(resumeData, enhancements, res);
        
    } catch (error) {
        console.error('PDF generation error:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// ATS score only
app.post('/api/ats-score', (req, res) => {
    try {
        const { resumeData } = req.body;
        
        if (!resumeData) {
            return res.status(400).json({ success: false, error: 'No resume data provided' });
        }
        
        const atsScore = calculateATSScore(resumeData);
        
        res.json({
            success: true,
            atsScore: atsScore
        });
        
    } catch (error) {
        console.error('ATS score error:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// ===== NEW CHAT ENDPOINT (ADDED) =====
app.post('/api/chat', (req, res) => {
    try {
        const { message, resumeData } = req.body;
        
        if (!message) {
            return res.status(400).json({ success: false, error: 'No message provided' });
        }
        
        console.log('💬 Chat message received:', message);
        
        // Generate response based on message and resume data
        let response = '';
        const lowerMsg = message.toLowerCase();
        
        if (lowerMsg.includes('score') || lowerMsg.includes('ats')) {
            const score = resumeData?.atsScore?.score || 75;
            response = `Your current ATS score is ${score}/100. To improve it, focus on adding more keywords, including metrics in your experience, and strengthening your summary section.`;
        }
        else if (lowerMsg.includes('skill')) {
            const skills = resumeData?.data?.skills || ['JavaScript', 'Python', 'React'];
            response = `Based on your profile, I recommend adding these skills: ${skills.join(', ')}. Also consider cloud platforms (AWS, Azure) and version control (Git).`;
        }
        else if (lowerMsg.includes('experience') || lowerMsg.includes('work')) {
            response = `To make your experience stand out: \n• Use strong action verbs (Led, Developed, Implemented)\n• Include numbers and metrics (increased by 30%, managed 5 people)\n• Focus on achievements, not just responsibilities`;
        }
        else if (lowerMsg.includes('summary') || lowerMsg.includes('objective')) {
            response = `A strong summary should: \n• Be 3-4 sentences\n• Highlight your top skills\n• Mention years of experience\n• Include career achievements\n• Be tailored to the job you want`;
        }
        else if (lowerMsg.includes('project')) {
            response = `For projects, include:\n• Technologies used\n• Your specific role\n• Challenges overcome\n• Results and impact\n• Link to live demo or GitHub`;
        }
        else if (lowerMsg.includes('education')) {
            response = `In your education section, include:\n• Degree and major\n• University name\n• Graduation year\n• Relevant coursework\n• GPA (if 3.5+)\n• Honors and achievements`;
        }
        else if (lowerMsg.includes('hello') || lowerMsg.includes('hi')) {
            response = `Hello! I'm your AI resume assistant. I can help you with:\n• Improving your ATS score\n• Enhancing skills section\n• Writing better experience descriptions\n• Creating impactful project summaries\n• Optimizing your summary\n• Education section tips\n\nWhat would you like help with?`;
        }
        else {
            response = `I can help you improve your resume! Try asking about:\n• "How to improve my ATS score?"\n• "Skills suggestions"\n• "Experience section tips"\n• "Summary writing"\n• "Project descriptions"\n• "Education section"`;
        }
        
        res.json({
            success: true,
            response: response,
            timestamp: new Date().toISOString()
        });
        
    } catch (error) {
        console.error('Chat error:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// Error handler
app.use((err, req, res, next) => {
    console.error('Server error:', err);
    res.status(500).json({ success: false, error: err.message });
});

const PORT = 5000;
app.listen(PORT, '0.0.0.0', () => {
    console.log('\n' + '='.repeat(60));
    console.log('🚀 AI RESUME BUILDER SERVER');
    console.log('='.repeat(60));
    console.log(`✅ Server running on port ${PORT}`);
    console.log(`📡 Local URL: http://localhost:${PORT}`);
    console.log(`📡 Network IP: http://${ipAddresses[0] || '192.168.x.x'}:${PORT}`);
    console.log('='.repeat(60));
    console.log(`📤 Upload endpoint: http://localhost:${PORT}/api/upload`);
    console.log(`🤖 AI Enhancement: Active (Mock Mode)`);
    console.log(`💬 Chat Assistant: Active`);
    console.log(`📊 ATS Scoring: Active`);
    console.log(`📥 PDF Download: Active`);
    console.log('='.repeat(60) + '\n');
});